name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: gtrunsec
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run Flake Show
        run: nix -Lv flake show

      - name: Build Doc
        run: nix develop .#doc --show-trace --command -- mkdoc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ./docs/publish/public
